[package]
name = "qdrust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.18.0"
threadpool = "1.8.1"
dyn-clone = "1.0.20"
rayon = "1.10.0"
